/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectohotel;
import java.util.Vector;
import java.util.Iterator;
import javax.swing.JOptionPane;
/**
 *
 * @author Robin Mita
 */
public class Empleado extends javax.swing.JFrame {

    
      Vector <ClaseEmpleado>ArregloEmpleado;
     
    public Empleado(Vector <ClaseEmpleado>a) {
        initComponents();
        ArregloEmpleado=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        rfNit = new javax.swing.JTextField();
        tfCorreoElectronico = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        tfTelefono = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Reporte = new javax.swing.JTextArea();
        btBuscar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Registro de nuevo empleado");

        jLabel2.setText("Nombre:");

        jLabel4.setText("Nit");

        jLabel6.setText("Correo:");

        jLabel7.setText("Direccion");

        tfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDireccionActionPerformed(evt);
            }
        });

        jLabel10.setText("Telefono");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Reporte.setColumns(20);
        Reporte.setRows(5);
        jScrollPane2.setViewportView(Reporte);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        jButtonVer.setText("Ver datos");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rfNit, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVer)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rfNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGuardar)
                            .addComponent(jButtonVer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBuscar)
                            .addComponent(btEliminar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void tfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDireccionActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
         if (evt.getSource()==btBuscar)
        {
            ClaseEmpleado c=BuscarEmpleado(rfNit.getText());
            if (c!=null)
                Reporte.setText(c.getNit()+" "+c.getNombre()+" "+c.getDireccion()+" "+c.getTelefono()+" "+c.getCorreo()+"\n");
            
            
            
//JOptionPane.showMessageDialog(null, "El campo de nit esta vacio");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
         if(evt.getSource()==btGuardar)
      {
         if (rfNit.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Ingrese un Nit");
        }
        else
        {
            if(evt.getSource()==btGuardar)
            {
                if (buscarNit(rfNit.getText())== false)
                    {
                     ClaseEmpleado emp= new ClaseEmpleado();
                     emp.setNit(rfNit.getText());
                     emp.setNonbre(tfNombre.getText());
                     emp.setDireccion(tfDireccion.getText());
                     emp.setTelefono(tfTelefono.getText());
                     emp.setCorreo(tfCorreoElectronico.getText());
                     ArregloEmpleado.add(emp);
                     rfNit.setText("");
                     tfNombre.setText("");
                     tfDireccion.setText("");
                     tfTelefono.setText("");
                     tfCorreoElectronico.setText("");

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Nit ya existe.");
                        rfNit.setText("");
                        tfNombre.setText("");
                        tfTelefono.setText("");
                        tfDireccion.setText("");
                        tfCorreoElectronico.setText("");
                                                

                                                

                    }            
            }
        }        

          
      }   
      }
      
       
        private boolean buscarNit(String n){
        boolean encontrado = false;
        ClaseEmpleado empl3;
        Iterator<ClaseEmpleado>itr=ArregloEmpleado.iterator();
        while(itr.hasNext())
        {
            empl3=itr.next();
            
            if (n.compareTo(empl3.getNit())==0)
            {
                encontrado=true;
            }
        }
        return encontrado;
 
    }//GEN-LAST:event_btGuardarActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
       Reporte.setText("");
        if(evt.getSource()==jButtonVer)
        {
            ClaseEmpleado e2;
            Iterator<ClaseEmpleado>itr=ArregloEmpleado.iterator();
            while(itr.hasNext())
            {
                e2=itr.next();
                Reporte.append(e2.getNit()+" "+e2.getNombre()+" "+e2.getDireccion()+" "+e2.getTelefono()+" "+e2.getCorreo()+"\n");
            }
        }
    }   
        
    
    
    private ClaseEmpleado BuscarEmpleado(String c)
    {
       ClaseEmpleado emp2;
       Iterator<ClaseEmpleado>itr=ArregloEmpleado.iterator();
       while (itr.hasNext())
       {
           emp2=itr.next();
           
           if(rfNit.getText().equals(emp2.getNit()))
           {
               return emp2;
           }
       }
       return null;
   
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
           if(evt.getSource()==btEliminar)
       {
           ClaseEmpleado emp=BuscarEmpleado(rfNit.getText());
           if (emp!=null)
               if(ArregloEmpleado.contains(emp))
               {
                   ArregloEmpleado.remove(emp);
                   rfNit.setText(" ");
                   tfNombre.setText("");
                   tfDireccion.setText("");
                   tfTelefono.setText("");
                   tfCorreoElectronico.setText("");
                   rfNit.requestFocus();
               }
       }
        
                 
        
    }//GEN-LAST:event_btEliminarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         if (rfNit.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(null, "Ingrese un Código");
       }
       else
       {
           if(buscarNit(rfNit.getText())==true)
           {
               ClaseEmpleado emp4;
               Integer count=0;
               Iterator<ClaseEmpleado>itr=ArregloEmpleado.iterator();
               while(itr.hasNext())
               {
                   count++;
                   emp4=itr.next();
                   if(rfNit.getText().compareTo(emp4.getNit())==0)
                   {
                     emp4.setNit(rfNit.getText());
                     emp4.setNonbre(tfNombre.getText());
                     emp4.setDireccion(tfDireccion.getText()); 
                     emp4.setTelefono(tfTelefono.getText());
                     emp4.setCorreo(tfCorreoElectronico.getText());
                     
                     Reporte.setText("");
                     ClaseEmpleado emp3;
                     Iterator<ClaseEmpleado>itr1=ArregloEmpleado.iterator();
                     while(itr1.hasNext())
                     {
                         emp3=itr1.next();
                         Reporte.append(emp3.getNit()+" "+emp3.getNombre()+" "+emp3.getDireccion()+" "+emp3.getTelefono()+" "+emp3.getCorreo()+"\n");
                     }
                   }
               }
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Nit no existe");
           }
       }
    }//GEN-LAST:event_jButton5ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextArea Reporte;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField rfNit;
    private javax.swing.JTextField tfCorreoElectronico;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
