/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectohotel;
import java.util.Vector;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Robin Mita
 */
public class Proveedor extends javax.swing.JFrame {
Vector <ClaseProveedor>ArregloProveedor;
    /**
     * Creates new form Proveedor
     */
    public Proveedor(Vector <ClaseProveedor>a) {
        initComponents();
        ArregloProveedor=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfCorreoElectronico = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reporte = new javax.swing.JTextArea();
        jButtonVer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfNit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Registro Proveedor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Correo Electronico");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Direccion");

        tfCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCorreoElectronicoActionPerformed(evt);
            }
        });

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        Reporte.setColumns(20);
        Reporte.setRows(5);
        jScrollPane1.setViewportView(Reporte);

        jButtonVer.setText("Ver datos");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nit");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btGuardar)
                                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGuardar)
                            .addComponent(jButtonVer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btEliminar)
                            .addComponent(btBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cancelar)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCorreoElectronicoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
       dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
       
        Reporte.setText("");
        if(evt.getSource()==jButtonVer)
        {
            ClaseProveedor c2;
            Iterator<ClaseProveedor>itr=ArregloProveedor.iterator();
            while(itr.hasNext())
            {
                c2=itr.next();
                Reporte.append("Nit: "+c2.getNit()+"\n Nombre: "+c2.getNombre()+"\n Dirección: "+c2.getDireccion()+"\n Telefono:"+c2.getTelefono()+"\n Correo: "+c2.getCorreo()+"\n \n");
            }
        }
        
        
    }//GEN-LAST:event_jButtonVerActionPerformed

      private boolean buscarNit(String n){
        boolean encontrado = false;
        ClaseProveedor cli3;
        Iterator<ClaseProveedor>itr=ArregloProveedor.iterator();
        while(itr.hasNext())
        {
            cli3=itr.next();
            if (n.compareTo(cli3.getNit())==0)
            {
                encontrado=true;
            }
        }
        return encontrado;
    }
    
    
    private ClaseProveedor BuscarProveedor(String c)
   {
       ClaseProveedor pro2;
       Iterator<ClaseProveedor>itr=ArregloProveedor.iterator();
       while (itr.hasNext())
       {
           pro2=itr.next();
           
           if(tfNit.getText().equals(pro2.getNit()))
           {
               return pro2;
           }
       }
       return null;
   }
    
    
    
    
    
    
    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
         if(evt.getSource()==btGuardar)
      {
         if (tfNit.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "El campo de nit esta vacio");
        }
        else
        {
            if(evt.getSource()==btGuardar)
            {
                if (buscarNit(tfNit.getText())== false)
                    {
                     ClaseProveedor cli= new ClaseProveedor();
                     cli.setNit(tfNit.getText());
                     cli.setNonbre(tfNombre.getText());
                     cli.setDireccion(tfDireccion.getText());
                     cli.setTelefono(tfTelefono.getText());
                     cli.setCorreo(tfCorreoElectronico.getText());
                     ArregloProveedor.add(cli);
                     tfNit.setText("");
                     tfNombre.setText("");
                     tfDireccion.setText("");
                     tfTelefono.setText("");
                     tfCorreoElectronico.setText("");


                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "El nit ya fue registrado anteriormente");
                        tfNit.setText("");
                        tfNombre.setText("");
                        tfDireccion.setText("");
                        tfTelefono.setText("");
                        tfCorreoElectronico.setText("");
                                                

                                                

                    }            
            }
        }        

          
          
      }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
       if (evt.getSource()==btBuscar)
        {
            ClaseProveedor c=BuscarProveedor(tfNit.getText());
            if (c!=null)
                Reporte.setText("Nit: "+c.getNit()+"\n Nombre: "+c.getNombre()+"\n Dirección: "+c.getDireccion()+"\n Telefono:"+c.getTelefono()+"\n Correo: "+c.getCorreo()+"\n ");
            
            
            
//JOptionPane.showMessageDialog(null, "El campo de nit esta vacio");
        }
       
   
        
        
        
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
                 if(evt.getSource()==btEliminar)
       {
           ClaseProveedor pro=BuscarProveedor(tfNit.getText());
           if (pro!=null)
               if(ArregloProveedor.contains(pro))
               {
                   ArregloProveedor.remove(pro);
                   tfNit.setText(" ");
                   tfNombre.setText("");
                   tfDireccion.setText("");
                   tfTelefono.setText("");
                   tfCorreoElectronico.setText("");
                   tfNit.requestFocus();
               }
       }
        
                 
        
        
    }//GEN-LAST:event_btEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tfNit.getText().isEmpty())
       {
           JOptionPane.showMessageDialog(null, "Ingrese un Código");
       }
       else
       {
           if(buscarNit(tfNit.getText())==true)
           {
               ClaseProveedor pro4;
               Integer count=0;
               Iterator<ClaseProveedor>itr=ArregloProveedor.iterator();
               while(itr.hasNext())
               {
                   count++;
                   pro4=itr.next();
                   if(tfNit.getText().compareTo(pro4.getNit())==0)
                   {
                     pro4.setNit(tfNit.getText());
                     pro4.setNonbre(tfNombre.getText());
                     pro4.setDireccion(tfDireccion.getText()); 
                     pro4.setTelefono(tfTelefono.getText());
                     pro4.setCorreo(tfCorreoElectronico.getText());
                     
                     Reporte.setText("");
                     ClaseProveedor pro3;
                     Iterator<ClaseProveedor>itr1=ArregloProveedor.iterator();
                     while(itr1.hasNext())
                     {
                         pro3=itr1.next();
                         Reporte.append("Nit: "+pro3.getNit()+"\n Nombre: "+pro3.getNombre()+"\n Dirección: "+pro3.getDireccion()+"\n Telefono:"+pro3.getTelefono()+"\n Correo: "+pro3.getCorreo()+"\n ");
                     }
                   }
               }
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Nit no existe");
           }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextArea Reporte;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfCorreoElectronico;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNit;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
