/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectohotel;


import java.util.Iterator;
import java.util.Vector;

/**
 *
 * @author Robin Mita
 */
public class Reporte extends javax.swing.JFrame {
Vector <ClaseCliente>ArregloCliente;
Vector <ClaseProveedor>ArregloProveedor;
    /**
     * Creates new form Reportes
     */
    public Reporte(Vector <ClaseCliente>a,Vector <ClaseProveedor>p) {
        initComponents();
        ArregloCliente=a;
        ArregloProveedor=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btReporteCliente = new javax.swing.JButton();
        ReporteEmpleado = new javax.swing.JButton();
        ReporteFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reporte = new javax.swing.JTextArea();
        btCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ReporteProveedores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btReporteCliente.setText("Reporte de clientes");
        btReporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporteClienteActionPerformed(evt);
            }
        });

        ReporteEmpleado.setText("Reporte de empleado");

        ReporteFactura.setText("Historial de Factura");

        Reporte.setColumns(20);
        Reporte.setRows(5);
        jScrollPane1.setViewportView(Reporte);

        btCerrar.setText("Cerrar");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Reportes");

        ReporteProveedores.setText("Reporte de proveedores ");
        ReporteProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReporteFactura)
                    .addComponent(ReporteEmpleado)
                    .addComponent(btReporteCliente)
                    .addComponent(ReporteProveedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCerrar)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btReporteCliente)
                .addGap(32, 32, 32)
                .addComponent(ReporteEmpleado)
                .addGap(30, 30, 30)
                .addComponent(ReporteProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReporteFactura)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCerrar)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btReporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporteClienteActionPerformed
          Reporte.setText("");
        if(evt.getSource()==btReporteCliente)
        {
            ClaseCliente c2;
            Iterator<ClaseCliente>itr=ArregloCliente.iterator();
           
            while(itr.hasNext())
            {
                c2=itr.next();
                Reporte.append(c2.getNombre()+" "+c2.getApellido()+" "+c2.getNit()+" "+c2.getDpi()+" "+c2.getEdad()+" "+c2.getDireccion()+" "+c2.getTelefono()+" "+c2.getCorreo()+"\n");
            }
        }
    
        
        
    }//GEN-LAST:event_btReporteClienteActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btCerrarActionPerformed

    private void ReporteProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteProveedoresActionPerformed
       
        Reporte.setText("");
        if(evt.getSource()==ReporteProveedores)
        {
            ClaseProveedor c2;
            Iterator<ClaseProveedor>itr=ArregloProveedor.iterator();
            while(itr.hasNext())
            {
                c2=itr.next();
                Reporte.append(c2.getNombre()+" "+c2.getDireccion()+" "+c2.getTelefono()+" "+c2.getCorreo()+"\n");
            }
        }
    }//GEN-LAST:event_ReporteProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Reporte;
    private javax.swing.JButton ReporteEmpleado;
    private javax.swing.JButton ReporteFactura;
    private javax.swing.JButton ReporteProveedores;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btReporteCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
